export const DIFFICULTY_MIN = 1;
export const DIFFICULTY_MAX = 10;
export const DIFFICULTY_MEAN_REVERSION = 5;

export const STABILITY_MIN = 0.1;
export const STABILITY_MAX = 36500;

export const MINUTE_IN_DAYS = 1 / 1440;
export const REVIEW_SCHEDULE_FLOOR_DAYS = 0.5;
export const RELEARNING_SCHEDULE_FLOOR_DAYS = 10 * MINUTE_IN_DAYS;
export const LEARNING_MAX_SCHEDULE_DAYS = 1;
export const RELEARNING_MAX_SCHEDULE_DAYS = 2;
export const REVIEW_STABILITY_OUTLIER_MULTIPLIER = 12;
export const REVIEW_STABILITY_OUTLIER_FLOOR_DAYS = 120;
export const REVIEW_INVALID_DUE_STABILITY_FALLBACK_MAX_DAYS = 7;

export const WORD_MAX_LENGTH = 80;
export const MEANING_MAX_LENGTH = 180;
export const NOTES_MAX_LENGTH = 240;
